// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xupeU91m9Esn3f-XiDD4kjWIZ2qMgDQ',
    appId: '1:7825913499:web:f2ce029523d0aae6a7783e',
    messagingSenderId: '7825913499',
    projectId: 'asroostore-27d04',
    authDomain: 'asroostore-27d04.firebaseapp.com',
    storageBucket: 'asroostore-27d04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuyOSPECmSdNhFn_1JFTwnCsR-l3TYWM',
    appId: '1:7825913499:android:0419db94ce372b33a7783e',
    messagingSenderId: '7825913499',
    projectId: 'asroostore-27d04',
    storageBucket: 'asroostore-27d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCs9_nOmEGC6l1WrgCWdjAC6yw2h1Qy4E',
    appId: '1:7825913499:ios:59932f03e89c438ca7783e',
    messagingSenderId: '7825913499',
    projectId: 'asroostore-27d04',
    storageBucket: 'asroostore-27d04.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCs9_nOmEGC6l1WrgCWdjAC6yw2h1Qy4E',
    appId: '1:7825913499:ios:59932f03e89c438ca7783e',
    messagingSenderId: '7825913499',
    projectId: 'asroostore-27d04',
    storageBucket: 'asroostore-27d04.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9xupeU91m9Esn3f-XiDD4kjWIZ2qMgDQ',
    appId: '1:7825913499:web:16226da5cdde5d0ca7783e',
    messagingSenderId: '7825913499',
    projectId: 'asroostore-27d04',
    authDomain: 'asroostore-27d04.firebaseapp.com',
    storageBucket: 'asroostore-27d04.firebasestorage.app',
  );
}
